### ISSUE TITLE
Issue when moving folder with subfolders

### ISSUE THREAD

**Issue by marcgrabow** [stringham/move-ts#11]
When using the move command on a folder that itself contains subfolders, the plugin will:

* update some references in other files to point to the new location
* fail in actually moving the folder

Example (before command):
```
* myfile.ts // has reference to myfolder/my subfolder/mysecondfile.ts
* myfolder
  * my subfolder
    * mysecondfile.ts
* another folder
```

**executing the move command to move "myfolder" into "another folder"**

Example (after command):
```
* myfile.ts // has updated reference to anotherfolder/myfolder/my subfolder/mysecondfile.ts
* myfolder
  * my subfolder
    * mysecondfile.ts
* another folder
```

Which results in a state that fails on compiling.

Thanks for the plugin, really helpful!

**Comment by stringham** [comment]
I tried following your reproduction steps, but things seemed to work. Is there something I'm missing?

File structure:
```
* myfile.ts
* myfolder
  * my subfolder
    * mysecondfile.ts
* another folder
```

```ts
//myfile.ts
import {Foo} from './myfolder/my subfolder/secondfile';
```

```ts
//secondfile.ts
export const Foo = 4;
```

**Move `myfolder` into `another folder`**

File structure is now:
```
* myfile.ts
* another folder
  * myfolder
    * my subfolder
      * mysecondfile.ts
```

and `myfile.ts` looks like:
```ts
//myfile.ts
import {Foo} from './another folder/myfolder/my subfolder/secondfile';
```

**Comment by stringham** [comment]
Since I am not able to reproduce and have not heard back, I am going to close this issue for now.
