### ISSUE TITLE
Move TS declarations to existing file with import update

### ISSUE THREAD

**Issue by musikobios** [stringham/move-ts#37]
Hello there!
This is an ask for new feature not an actual issue.
It would be really helpful to move some TS declarations to already existing files eg. move from `a.ts` and append to `b.ts`, and auto update the imports of `c.ts`.
```diff
// (a.ts)
-export type MyType {
-  x: string;
-  y: boolean;
-  z: object;
-}
```
and append to existing `b.ts`:
```diff
// b.ts
export type OldType {
  field: number;
}

+export type MyType {
+  x: string;
+  y: boolean;
+  z: object;
+}
```
So the imports of `c.ts` will now become:
```diff
// c.ts
- import MyType from "./a.ts"
+ import MyType from "./b.ts"
```

**Comment by Papooch** [comment]
This is already a built-in feature of VSCode.
Select code, press Ctrl/Cmd+., select "Move to file". All imports everywhere will be updated.
![image](https://github.com/stringham/move-ts/assets/46406259/e180ad82-9228-4366-a034-9e40b8769397)
