### ISSUE TITLE
Seems to miss files inside index.ts barrells

### ISSUE THREAD

**Issue by scottwio** [stringham/move-ts#5]
First off thanks for the plugin it's amazing, speeds up refactoring 10 times over. I have however notice a issue, whenever I rename or move a file the plugin it will not move rename the file inside index.ts barrel files. For example I have this barrels 

~~~
shared/index.ts
export { AppStateService } from './state/app-state.service';
export { SpinnerService } from './state/spinner.service';
...
...
...
...
~~~

Renaming  './state/spinner.service' using move-ts will correctly rename the file in anything that is referencing the files directly with  './state/spinner.service' but it will miss anything referencing it for './share/index.ts'. Would be great if this plugin could work with barrels.

**Comment by stringham** [comment]
@scottwio so the problem is that it does not update relative paths in `export` statements?

If you rename `./state/spinner.service`, to `./state/superspinner.service`, you want the index.ts barrel to have:


```typescript
export { AppStateService } from './state/app-state.service';
export { SpinnerService } from './state/superspinner.service';
```

Is that right?

**Comment by scottwio** [comment]
Correct

**Comment by stringham** [comment]
@scottwio try updating the extension and let me know if it doesn't work for you.

**Comment by scottwio** [comment]
Works perfectly. Quickest reply / code updated ever, thanks.
