### ISSUE TITLE
support move folder when in active in exlorer

### ISSUE THREAD

**Issue by wclr** [stringham/move-ts#8]
When being active on a folder in explorer command should propose to rename/move folder not current active file if it is possible?

Also, it won't move folder if it does exist, probably in this case just should move content. maybe ask about what to do with existing files (overwrite/remove?

**Comment by stringham** [comment]
If you right click on the folder in the explorer it gives you the option to move that folder with move-ts.

**Comment by wclr** [comment]
Yes but command `ctlr+shifp+p` propose to move file not folder when focus is on folder in exlorer.

**Comment by wclr** [comment]
Also there is an error if folder exists, that could be handled.

**Comment by stringham** [comment]
Yeah, if the folder already exists we could check that there would be no conflicts when moving the files.

I'd welcome a pull request.

I don't think there's an API available to tell what folder is active in the explorer.
