### ISSUE TITLE
Handle case when compiled *.d.ts is nearby

### ISSUE THREAD

**Issue by wclr** [stringham/move-ts#9]
It would be nice if move-ts could handle following case when compiled versions are nearby with the source:

```
some-file.ts --> moving this
some-file.d.ts
some-file.js
```

after moving `some-file.ts` references in other files do not change, probably because there is no error and it is importing now `some-file.d.ts`, which is probably not desirable in such cases. 

Maybe it should move compiled versions with `.ts` file, maybe to ask about it or add an option if not introduce this behavior by default.
 
Current workaround would be to remove `.d.ts/js` before `ts-move`

**Comment by stringham** [comment]
I think this should work. Can you share a reproducible case?

**Comment by wclr** [comment]
What should work? It doesn't. 
1) corresponding `.d.ts/js` files are not moved, 
2) imports in other files are not changed.

Just try it.

**Comment by stringham** [comment]
I would not expect:
1. for it to move `.d.ts/js` files.

I would expect that:
2. Imports in other files are changed.

I just published a new version that should fix imports in other files being changed. Try updating and let me know if that doesn't work for you.

I'm not convinced that moving the corresponding compiled targets would be an expected behavior.

**Comment by wclr** [comment]
No it doesn't work for me. In example renameing `config-map.ts` -> `configMap.ts

![ts-move](https://user-images.githubusercontent.com/736697/27991655-b2100008-6497-11e7-9665-6367c2c8fc48.gif)
`
It doesn't move `d.ts/.js` and doesn't change import.

> I'm not convinced that moving the corresponding compiled targets would be an expected behavior.

That why I proposed to ask (prompt) about it but also I would add a setting. In most cases, I would expect it to be desired default behavior at least for `.d.ts` file, because without this move it won't work properly.

**Comment by stringham** [comment]
There is code that assumes that the `typings` directory is not part of the workspace that you would want to manually update (since it's part of a build output)

```typescript
files = files.filter((f) => {
    return f.fsPath.indexOf('typings') === -1 &&
        f.fsPath.indexOf('node_modules') === -1 &&
        f.fsPath.indexOf('jspm_packages') === -1;
});
```

We could make the exclude directories a configuration option.

**Comment by stringham** [comment]
If you'd like it to handle files in generated folders, please open another issue.

**Comment by wclr** [comment]
Ok thanks)
